# Generated by Django 4.1.9 on 2023-05-17 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("categoryId", models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ("title", models.CharField(max_length=1024)),
                ("seo", models.TextField(blank=True, null=True)),
                ("adult", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("children", models.ManyToManyField(blank=True, related_name="parent_cats", to="category.category")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_categories",
                        to="category.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryAnalytics",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("totalProducts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="category.category"),
                ),
            ],
        ),
    ]
