# Generated by Django 4.1.9 on 2023-05-20 12:37

from django.db import migrations, models
import uzum.product.models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryanalytics",
            name="date_pretty",
            field=models.CharField(
                blank=True, db_index=True, default=uzum.product.models.get_today_pretty, max_length=255, null=True
            ),
        ),
    ]
