# Generated by Django 4.1.9 on 2023-05-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_category_descendants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoryanalytics",
            old_name="totalProducts",
            new_name="total_products",
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="total_orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="total_orders_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="total_products_with_sales",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="total_reviews",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="total_shops",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="total_shops_with_sales",
            field=models.IntegerField(default=0),
        ),
    ]
