# Generated by Django 4.1.9 on 2023-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0004_rename_totalproducts_categoryanalytics_total_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryanalytics",
            name="total_products_with_reviews",
            field=models.IntegerField(default=0),
        ),
    ]
