# Generated by Django 4.1.9 on 2023-06-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0006_alter_category_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryanalytics",
            name="average_rating",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_orders",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_orders_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_products_with_reviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_products_with_sales",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_reviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_shops",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_shops_with_sales",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
