# Generated by Django 4.1.9 on 2023-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0007_alter_categoryanalytics_average_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryanalytics",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="categoryanalytics",
            name="total_products_with_reviews",
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="average_order_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="average_product_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categoryanalytics",
            name="average_purchase_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_orders",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_orders_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_products_with_sales",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_reviews",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_shops",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_shops_with_sales",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
