# Generated by Django 4.1.9 on 2023-07-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0008_remove_categoryanalytics_average_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ancestors",
            field=models.TextField(blank=True, null=True),
        ),
    ]
