# Generated by Django 4.1.9 on 2023-07-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0010_alter_categoryanalytics_total_orders_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryanalytics",
            name="average_order_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="average_product_rating",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="average_purchase_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_orders",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_products_with_sales",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_reviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_shops",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="categoryanalytics",
            name="total_shops_with_sales",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
