# Generated by Django 4.1.9 on 2023-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0011_alter_categoryanalytics_average_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="title_ru",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
