# Generated by Django 4.1.9 on 2023-08-01 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0012_category_title_ru"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="children",
        ),
    ]
