# Generated by Django 4.1.9 on 2023-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0013_remove_category_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ancestors_ru",
            field=models.TextField(blank=True, null=True),
        ),
    ]
