# Generated by Django 4.1.9 on 2023-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0015_categoryanalytics_daily_revenue"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryanalytics",
            name="daily_orders_amount",
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
