# Generated by Django 4.1.9 on 2023-05-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badge", "0001_initial"),
        ("banner", "0002_initial"),
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="product",
            name="reviews",
        ),
        migrations.AddField(
            model_name="productanalytics",
            name="badges",
            field=models.ManyToManyField(db_index=True, to="badge.badge"),
        ),
        migrations.AddField(
            model_name="productanalytics",
            name="banners",
            field=models.ManyToManyField(db_index=True, to="banner.banner"),
        ),
    ]
