# Generated by Django 4.1.9 on 2023-05-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badge", "0001_initial"),
        ("product", "0003_remove_product_badges_remove_product_reviews_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalytics",
            name="badges",
            field=models.ManyToManyField(db_index=True, related_name="products", to="badge.badge"),
        ),
    ]
