# Generated by Django 4.1.9 on 2023-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_productanalytics_badges"),
    ]

    operations = [
        migrations.AddField(
            model_name="productanalytics",
            name="available_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productanalytics",
            name="orders_money",
            field=models.IntegerField(default=0),
        ),
    ]
