# Generated by Django 4.1.9 on 2023-06-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_productanalytics_available_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
