# Generated by Django 4.1.9 on 2023-06-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="productanalytics",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productanalytics",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
