# Generated by Django 4.1.9 on 2023-06-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_productanalytics_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalytics",
            name="position",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productanalytics",
            name="score",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
