# Generated by Django 4.1.9 on 2023-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_alter_productanalytics_orders_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productanalytics",
            old_name="position",
            new_name="position_in_category",
        ),
        migrations.RemoveField(
            model_name="productanalytics",
            name="score",
        ),
        migrations.AddField(
            model_name="productanalytics",
            name="position_in_shop",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
