# Generated by Django 4.1.9 on 2023-07-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_rename_position_productanalytics_position_in_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAnalyticsView",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("product_title", models.CharField(max_length=255)),
                ("product_characteristics", models.TextField(blank=True, null=True)),
                ("orders_amount", models.IntegerField()),
                ("product_available_amount", models.IntegerField()),
                ("reviews_amount", models.IntegerField()),
                ("rating", models.FloatField()),
                ("shop_title", models.CharField(max_length=255)),
                ("shop_link", models.TextField()),
                ("category_id", models.IntegerField()),
                ("photos", models.TextField(blank=True, null=True)),
                ("date_pretty", models.CharField(max_length=255)),
                ("position_in_category", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "uzum_product_analytics_view",
                "managed": False,
            },
        ),
    ]
