# Generated by Django 4.1.9 on 2023-06-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_rename_position_productanalytics_position_in_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAnalyticsView",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.IntegerField()),
                ("product_title", models.CharField(max_length=255)),
                ("orders_amount", models.IntegerField()),
                ("available_amount", models.IntegerField()),
                ("reviews_amount", models.IntegerField()),
                ("shop_title", models.CharField(max_length=255)),
                ("shop_link", models.TextField()),
                ("badge_text", models.TextField(blank=True, null=True)),
                ("badge_background_color", models.CharField(blank=True, max_length=255, null=True)),
                ("badge_text_color", models.CharField(blank=True, max_length=255, null=True)),
                ("purchase_price", models.FloatField()),
                ("full_price", models.FloatField()),
                ("category_id", models.IntegerField()),
                ("photos", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "uzum_product_analytics_view",
                "managed": False,
            },
        ),
    ]
