# Generated by Django 4.1.9 on 2023-07-01 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_productanalyticsview"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productanalyticsview",
            table="product_sku_analytics",
        ),
    ]
