# Generated by Django 4.1.9 on 2023-07-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_alter_productanalyticsview_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="productanalytics",
            name="position",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
