# Generated by Django 4.1.9 on 2023-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_productanalytics_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="productanalytics",
            name="average_purchase_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
