# Generated by Django 4.1.9 on 2023-07-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_productanalytics_average_purchase_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
