# Generated by Django 4.1.9 on 2023-07-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalytics",
            name="orders_money",
            field=models.FloatField(default=0.0),
        ),
    ]
