# Generated by Django 4.1.9 on 2023-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_alter_productanalytics_orders_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="title_ru",
            field=models.TextField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
