# Generated by Django 4.1.9 on 2023-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_product_title_ru"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestProductAnalyticsView",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("last_updated_at", models.DateTimeField()),
                ("latest_orders_money", models.DecimalField(decimal_places=2, max_digits=10)),
                ("latest_average_purchase_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("latest_orders_amount", models.IntegerField()),
            ],
            options={
                "db_table": "product_latest_analytics",
                "managed": False,
            },
        ),
    ]
