# Generated by Django 4.1.9 on 2023-09-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_alter_productanalytics_orders_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="productanalytics",
            name="score",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
