# Generated by Django 4.1.9 on 2023-10-05 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0023_productanalytics_delta_orders_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productanalytics",
            old_name="delta_orders_amount",
            new_name="real_orders_amount",
        ),
    ]
