# Generated by Django 4.1.9 on 2023-10-06 09:30

from django.db import migrations, models

import uzum.utils.general


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0025_alter_productanalytics_available_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalytics",
            name="date_pretty",
            field=models.CharField(
                blank=True, db_index=True, default=uzum.utils.general.get_today_pretty, max_length=255, null=True
            ),
        ),
    ]
