# Generated by Django 4.1.9 on 2023-10-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0028_remove_productanalytics_date_pretty_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalytics",
            name="orders_money",
            field=models.FloatField(default=0.0),
        ),
    ]
