# Generated by Django 4.1.9 on 2023-10-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0029_alter_productanalytics_orders_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="characteristics_ru",
            field=models.TextField(blank=True, null=True),
        ),
    ]
