# Generated by Django 4.1.9 on 2023-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0031_remove_product_characteristics_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productanalytics",
            name="daily_revenue",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
