# Generated by Django 4.1.9 on 2023-10-10 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0032_productanalytics_daily_revenue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productanalytics",
            name="real_orders_money",
        ),
    ]
