# Generated by Django 4.1.9 on 2023-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_remove_productanalytics_real_orders_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanalytics',
            name='positions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
