# Generated by Django 4.1.9 on 2023-10-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0003_alter_popularseaches_date_pretty"),
    ]

    operations = [
        migrations.AddField(
            model_name="popularseaches",
            name="words_ru",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
