# Generated by Django 4.1.9 on 2023-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("badge_id", models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("link", models.TextField(blank=True, null=True)),
                ("textColor", models.CharField(blank=True, max_length=255, null=True)),
                ("backgroundColor", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
