# Generated by Django 4.1.9 on 2023-06-29 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badge", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="badge",
            old_name="backgroundColor",
            new_name="background_color",
        ),
        migrations.RenameField(
            model_name="badge",
            old_name="textColor",
            new_name="text_color",
        ),
    ]
