# Generated by Django 4.1.9 on 2023-05-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0002_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopanalytics",
            name="banners",
            field=models.ManyToManyField(to="banner.banner"),
        ),
    ]
