# Generated by Django 4.1.9 on 2023-05-29 17:13

from django.db import migrations, models
from uzum.utils.general import get_today_pretty


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_shopanalytics_banners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopanalytics",
            name="date_pretty",
            field=models.CharField(blank=True, db_index=True, default=get_today_pretty, max_length=255, null=True),
        ),
    ]
