# Generated by Django 4.1.9 on 2023-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0005_categoryanalytics_total_products_with_reviews"),
        ("shop", "0003_alter_shopanalytics_date_pretty"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopanalytics",
            name="categories",
            field=models.ManyToManyField(to="category.category"),
        ),
    ]
