# Generated by Django 4.1.9 on 2023-06-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_shop_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopanalytics",
            name="daily_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shopanalytics",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
