# Generated by Django 4.1.9 on 2023-06-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_shopanalytics_daily_position_shopanalytics_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopanalytics",
            name="monthly_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shopanalytics",
            name="monthly_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="shopanalytics",
            name="weekly_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shopanalytics",
            name="weekly_score",
            field=models.FloatField(default=0),
        ),
    ]
