# Generated by Django 4.1.9 on 2023-06-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_shopanalytics_monthly_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopanalytics",
            name="daily_position",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shopanalytics",
            name="monthly_position",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shopanalytics",
            name="monthly_score",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shopanalytics",
            name="score",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shopanalytics",
            name="weekly_position",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shopanalytics",
            name="weekly_score",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
