# Generated by Django 4.1.9 on 2023-06-28 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_shopanalytics_daily_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopanalytics",
            name="daily_position",
        ),
        migrations.RemoveField(
            model_name="shopanalytics",
            name="monthly_position",
        ),
        migrations.RemoveField(
            model_name="shopanalytics",
            name="monthly_score",
        ),
        migrations.RemoveField(
            model_name="shopanalytics",
            name="score",
        ),
        migrations.RemoveField(
            model_name="shopanalytics",
            name="weekly_position",
        ),
        migrations.RemoveField(
            model_name="shopanalytics",
            name="weekly_score",
        ),
    ]
