# Generated by Django 4.1.9 on 2023-07-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_shopanalytics_average_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopanalytics",
            name="position",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shopanalytics",
            name="average_order_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="shopanalytics",
            name="average_purchase_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
