# Generated by Django 4.1.9 on 2023-07-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_shopanalytics_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopanalytics",
            name="categories",
        ),
        migrations.AddField(
            model_name="shopanalytics",
            name="category_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shopanalytics",
            name="total_orders",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
