# Generated by Django 4.1.9 on 2023-07-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_remove_shopanalytics_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopanalytics",
            name="category_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
