# Generated by Django 4.1.9 on 2023-07-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0008_remove_categoryanalytics_average_rating_and_more"),
        ("shop", "0013_alter_shopanalytics_category_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopanalytics",
            name="category_count",
        ),
        migrations.AddField(
            model_name="shopanalytics",
            name="categories",
            field=models.ManyToManyField(to="category.category"),
        ),
    ]
