# Generated by Django 4.1.9 on 2023-07-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_remove_shopanalytics_category_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopanalytics",
            name="total_revenue",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
