# Generated by Django 4.1.9 on 2023-08-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_shopanalytics_total_revenue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopAnalyticsTable",
            fields=[
                ("date_pretty", models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ("total_revenue", models.FloatField()),
                ("total_reviews", models.IntegerField()),
                ("total_orders", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "shop_analytics",
                "managed": False,
            },
        ),
    ]
