# Generated by Django 4.1.9 on 2023-09-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_shopanalyticstable"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopanalytics",
            name="monthly_total_orders",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="shopanalytics",
            name="monthly_total_revenue",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
