# Generated by Django 4.1.9 on 2023-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_shopanalytics_monthly_total_orders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopanalytics",
            name="real_orders_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shopanalytics",
            name="real_revenue",
            field=models.FloatField(default=0),
        ),
    ]
