# Generated by Django 4.1.9 on 2023-10-10 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_shopanalytics_real_orders_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shopanalytics",
            old_name="real_orders_amount",
            new_name="daily_orders",
        ),
        migrations.RenameField(
            model_name="shopanalytics",
            old_name="real_revenue",
            new_name="daily_revenue",
        ),
    ]
