# Generated by Django 4.1.9 on 2023-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_real_orders_amount_shopanalytics_daily_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopanalytics',
            name='positions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
