# Generated by Django 4.1.9 on 2023-10-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_shopanalytics_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopanalytics',
            name='banners',
        ),
    ]
