# Generated by Django 4.1.9 on 2023-10-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_shopanalytics_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAnalyticsRecent',
            fields=[
                ('seller_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('total_products', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_purchase_price', models.FloatField(blank=True, default=0, null=True)),
                ('rating', models.FloatField(default=0)),
                ('monthly_orders', models.IntegerField(blank=True, default=0, null=True)),
                ('monthly_revenue', models.FloatField(blank=True, default=0, null=True)),
                ('quarterly_orders', models.IntegerField(blank=True, default=0, null=True)),
                ('quarterly_revenue', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'shop_analytics_interval',
                'managed': False,
            },
        ),
    ]
