# Generated by Django 4.1.9 on 2023-10-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_shopanalyticsrecent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shopanalyticsrecent',
            table='combined_shop_analytics',
        ),
    ]
