# Generated by Django 4.1.9 on 2023-05-17 13:19

import uuid

import django.db.models.deletion
from django.db import migrations, models

from uzum.utils.general import get_today_pretty


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("badge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sku",
            fields=[
                ("sku", models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("barcode", models.CharField(blank=True, max_length=255, null=True)),
                ("charity_profit", models.FloatField(default=0)),
                ("payment_per_month", models.FloatField(default=0)),
                ("vat_amount", models.FloatField(default=0)),
                ("vat_price", models.FloatField(default=0)),
                ("vat_rate", models.FloatField(default=0)),
                ("video_url", models.TextField(blank=True, null=True)),
                ("characteristics", models.TextField(blank=True, null=True)),
                (
                    "discount_badge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="skus",
                        to="badge.badge",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="skus", to="product.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkuAnalytics",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("available_amount", models.IntegerField(default=0)),
                ("purchase_price", models.FloatField(default=0)),
                ("full_price", models.FloatField(blank=True, default=None, null=True)),
                (
                    "date_pretty",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=get_today_pretty,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="analytics", to="sku.sku"
                    ),
                ),
            ],
        ),
    ]
