# Generated by Django 4.1.9 on 2023-05-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skuanalytics",
            name="orders_amount",
            field=models.IntegerField(default=0),
        ),
    ]
