# Generated by Django 4.1.9 on 2023-06-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0004_alter_skuanalytics_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skuanalytics",
            name="purchase_price",
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
