# Generated by Django 4.1.9 on 2023-09-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0005_alter_skuanalytics_purchase_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestSkuAnalyticsView",
            fields=[
                ("sku_id", models.IntegerField(primary_key=True, serialize=False)),
                ("last_updated_at", models.DateTimeField()),
                ("latest_purchase_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("latest_orders_amount", models.IntegerField()),
                ("latest_available_amount", models.IntegerField()),
            ],
            options={
                "db_table": "sku_latest_analytics",
                "managed": False,
            },
        ),
    ]
