# Generated by Django 4.1.9 on 2023-10-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0006_latestskuanalyticsview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skuanalytics",
            name="available_amount",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
