# Generated by Django 4.1.9 on 2023-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0007_alter_skuanalytics_available_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="skuanalytics",
            name="delta_available_amount",
            field=models.IntegerField(default=0),
        ),
    ]
