# Generated by Django 4.1.9 on 2023-10-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0008_skuanalytics_delta_available_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skuanalytics",
            name="delta_available_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
