# Generated by Django 4.1.9 on 2023-10-07 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0009_alter_skuanalytics_delta_available_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skuanalytics",
            name="orders_amount",
        ),
    ]
