# Generated by Django 4.1.9 on 2023-10-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0010_remove_skuanalytics_orders_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="skuanalytics",
            name="orders_amount",
            field=models.IntegerField(default=0),
        ),
    ]
