# Generated by Django 4.1.9 on 2023-10-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0012_skuanalytics_orders_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skuanalytics",
            name="orders_amount",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="skuanalytics",
            name="orders_money",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="skuanalytics",
            name="purchase_price",
            field=models.FloatField(default=0),
        ),
    ]
