# Generated by Django 4.1.9 on 2023-06-25 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referred",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="referrals_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="referrals_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
