# Generated by Django 4.1.9 on 2023-08-11 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_id",
            new_name="account_id",
        ),
    ]
