# Generated by Django 4.1.9 on 2023-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="months",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Requested"), (2, "Created"), (3, "Performed"), (4, "Canceled")], default=1
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tariff",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("trial", "Trial"),
                    ("base", "Base"),
                    ("seller", "Seller"),
                    ("business", "Business"),
                ],
                default="base",
                max_length=10,
            ),
        ),
    ]
