# Generated by Django 4.1.9 on 2023-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_rename_payment_id_payment_account_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="account_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.IntegerField(default=85),
            preserve_default=False,
        ),
    ]
