# Generated by Django 4.1.9 on 2023-08-12 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0003_remove_payment_account_id_payment_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchatTransactionsModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("_id", models.CharField(max_length=255, null=True)),
                ("transaction_id", models.CharField(max_length=255, null=True)),
                ("order_id", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("time", models.BigIntegerField(blank=True, null=True)),
                ("perform_time", models.BigIntegerField(default=0, null=True)),
                ("cancel_time", models.BigIntegerField(default=0, null=True)),
                ("state", models.IntegerField(default=1, null=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at_ms", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
