# Generated by Django 4.1.9 on 2023-08-12 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0004_merchattransactionsmodel_delete_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchattransactionsmodel",
            name="order_id",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.FloatField(blank=True, null=True)),
                ("order_id", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="merchattransactionsmodel",
            name="order",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="payment.order"),
            preserve_default=False,
        ),
    ]
