# Generated by Django 4.1.9 on 2023-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_fingerprint_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(default="899643", max_length=6, unique=True),
        ),
    ]
