# Generated by Django 4.1.9 on 2023-06-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_fingerprint_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(default="abcdef", max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
