# Generated by Django 4.1.9 on 2023-05-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(default="5DC574", max_length=6, unique=True),
        ),
    ]
