# Generated by Django 4.1.9 on 2023-07-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_pro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_proplus",
            field=models.BooleanField(default=False),
        ),
    ]
