# Generated by Django 4.1.9 on 2023-07-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_is_pro_user_is_proplus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_developer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_pro",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_proplus",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
