# Generated by Django 4.1.9 on 2023-07-22 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_is_paid_user_trial_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_pro",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="trial_end",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 23, 4, 12, 37, 412228, tzinfo=datetime.timezone.utc),
                null=True,
            ),
        ),
    ]
