# Generated by Django 4.1.9 on 2023-08-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_shopanalyticstable"),
        ("users", "0015_alter_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="shop",
        ),
        migrations.AddField(
            model_name="user",
            name="is_enterprise",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="shops",
            field=models.ManyToManyField(blank=True, to="shop.shop"),
        ),
    ]
