# Generated by Django 4.1.9 on 2023-08-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_user_shop_user_is_enterprise_user_shops"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shops_updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
