# Generated by Django 4.1.9 on 2023-08-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_user_shops_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="shops_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
