# Generated by Django 4.1.9 on 2023-08-14 18:11

from django.db import migrations, models
import uzum.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_shops_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_enterprise",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_pro",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_proplus",
        ),
        migrations.RemoveField(
            model_name="user",
            name="trial_end",
        ),
        migrations.AddField(
            model_name="user",
            name="payment_date",
            field=models.DateTimeField(blank=True, default=uzum.users.models.get_one_day_later, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tariff",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("trial", "Trial"),
                    ("base", "Base"),
                    ("seller", "Seller"),
                    ("business", "Business"),
                ],
                default="trial",
                max_length=10,
            ),
        ),
    ]
