# Generated by Django 4.1.9 on 2023-08-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_is_enterprise_remove_user_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authentication_method',
            field=models.CharField(choices=[('STANDARD', 'Standard Registration'), ('GOOGLE', 'Google OAuth'), ('TELEGRAM', 'Telegram'), ('PHONE', 'Phone')], default='STANDARD', max_length=10),
        ),
    ]
