# Generated by Django 4.1.9 on 2023-09-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0021_productanalytics_score"),
        ("shop", "0016_shopanalyticstable"),
        ("users", "0020_user_authentication_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favourite_products",
            field=models.ManyToManyField(blank=True, related_name="favourite_products", to="product.product"),
        ),
        migrations.AddField(
            model_name="user",
            name="favourite_shops",
            field=models.ManyToManyField(blank=True, related_name="favourite_shops", to="shop.shop"),
        ),
    ]
