# Generated by Django 4.1.9 on 2023-09-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_alter_user_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_paid",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
